Vagrant.configure("2") do |config|
  # Configuração para encaminhamento da chave SSH
  config.ssh.forward_agent = true

  # Configuração das duas máquinas
  (1..2).each do |i|
    config.vm.define "srvweb#{i}" do |srvweb|
      # Configurações específicas da máquina
      srvweb.vm.box = "ubuntu/trusty64"  # Box Ubuntu 14.04 LTS
      srvweb.vm.hostname = "srvweb#{i}" # Definindo o hostname
      srvweb.vm.network "private_network", ip: "10.0.0.#{i + 10}", virtualbox__intnet: true

      # Limitando CPU e memória
      srvweb.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end

      # Configurações específicas para servidor web (máquinas 1 e 2)
      if i <= 2
        srvweb.vm.provision "shell", inline: <<-SHELL
        # CONFIGURANDO SOURCE.LIST
          sudo sed -i '/^#/d' /etc/apt/sources.list
          sudo sed -i 's/^deb-src/#deb-src/' /etc/apt/sources.list
          sudo sed -i '/^security.ubuntu.com/d' /etc/apt/sources.list

          sudo apt-get update
          sudo apt-get install -y apache2
        #PASSWORD DO ROOT
          echo "root:vagrant" | sudo chpasswd
        #PERMITINDO ROOT LOGIN
          sudo sed -i 's/^PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart
        SHELL
      end
    end
  end

  # Configurações específicas para o Ansible (máquina3)
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "ubuntu/trusty64"  # Box Ubuntu 14.04 LTS
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "10.0.0.13", virtualbox__intnet: true

    # Limitando CPU e memória
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    # Provisionamento do Ansible
    ansible.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y ansible sshpass
      sudo ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
    # Configurando o Ansible para acessar máquinas1 e máquinas2 por chave SSH
      sshpass -p "vagrant" ssh-copy-id -o StrictHostKeyChecking=no 10.0.0.11
      sshpass -p "vagrant" ssh-copy-id -o StrictHostKeyChecking=no 10.0.0.12
    SHELL
  end
end